[params]
  # Content adapters config for component projects
  [params.projectsAdapters]
    enable = false
    # Whether to show only public repos
    onlyPublic = true
    # Default categories and collections
    categories = []
    collections = []
    # Ignore repos in the ignore list
    ignoreList = []
    [params.projectsAdapters.params]
      hiddenFromHomePage = true
      # more font matter here ...

[module]
  [module.hugoVersion]
    extended = true
    min = "0.146.0"
