[params]
  # Content adapters config for component projects
  [params.projects_adapters]
    enable = false
    # Whether to show only public repos
    onlyPublic = true
    # Default categories and collections
    categories = []
    collections = []
    # Ignore repos in the ignore list
    ignoreList = []

[module]
  [module.hugoVersion]
    extended = true
    min = "0.132.0"