# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = 'component-projects'
license = 'MIT'
licenselink = 'https://github.com/hugo-fixit/component-projects/LICENSE'
description = 'A Hugo theme component with layout projects and shortcodes to display GitHub pinned card style repositories.'
min_version = "0.123.0"

# The home page of the theme, where the source can be found
homepage = 'https://github.com/hugo-fixit/component-projects'

# If you have a running demo of the theme
demosite = 'https://fixit.lruihao.cn/components/'

# Taxonomy terms
tags = ['layout', 'shortcodes']
features = ['github', 'repo-embed', 'projects']

# If the theme has a single author
[author]
  name = 'Lruihao'
  homepage = 'https://lruihao.cn'
